[package]
name = "tremble"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
thiserror = "2"

# TODO: Enable for "CSharp" feature only
[build-dependencies]
csbindgen = "1"